### ISSUE TITLE
Please Create Releases so we can use this Library with Maven as a dependency

### ISSUE THREAD

**Issue by goxr3plus** [mfischbo/java-discogs-client#4]
One very useful way to use this project is as Maven or Gradle Depedency . So you can make a release  https://github.com/mfischbo/java-discogs-client so we can use it with JitPack.io which allows to use any github project as library with Maven and Gradle :+1:

https://jitpack.io/#mfischbo/java-discogs-client

Waiting for your reponse :)

**Comment by mfischbo** [comment]
Thank you for using this library and pointing out the possibility of using jitpack as a repository for maven artifacts. I've created a release of what I would consider a 1.0.0 version of this library, even it does not support all the features of the official Discogs API.
